@Echo off


@rem --------------------------------------------------------------------------------
@rem ---
@rem ---   void main()
@rem ---
@rem ---   Creates a project structiure for gradle.
@rem ---

:main

	call:defineMacros
	call:resetErrorlevel
	call:defineConstants

	call:deleteFile %gradleSettingsFile2%
	call:deleteFile %gradleBuildFile2%

	echo initialize gradle settings ^(%gradleSettingsFile1%^)
	(
		echo /*
		echo  * The file settings.gradle was generated with NetBeans 25.
		echo  */
		echo.
		echo /*
		echo  * This file was generated by the Gradle 'init' task.
		echo  *
		echo  * The settings file is used to specify which projects to include in your build.
		echo  * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10/userguide/multi_project_builds.html in the Gradle documentation.
		echo  */
		echo.
		echo plugins {
		echo     // Apply the foojay-resolver plugin to allow automatic download of JDKs
		echo     id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
		echo }
		echo.
		echo rootProject.name ^= 'Numbers'
		echo include^('lib'^)
	) > "%gradleSettingsFile1%"


	@rem https://docs.gradle.org/current/samples/sample_building_java_applications.html
	@rem https://docs.gradle.org/current/samples/sample_building_java_libraries.html
	@rem https://discuss.gradle.org/t/how-to-link-a-static-library-in-build-gradle-file-for-a-nativelibraryspec/29205

	echo initialize gradle buildfile ^(%gradleBuildFile1%^)
	(
		echo /*
		echo  * The file gradle.build was generated with CoPilot.
		echo  */
		echo.
		echo plugins {
		echo     id 'java'
		echo }
		echo
		echo // Load project version from properties file
		echo def versionProps ^= new Properties^(^)
		echo file^('src/main/resources/numbers_version.properties'^).withInputStream { stream -^>
		echo     versionProps.load^(stream^)
		echo }
		echo project.version = versionProps.getProperty^('version'^)
		echo.
		echo group ^= 'jmul.math.numbers'
		echo.
		echo.
		echo java {
		echo     sourceCompatibility ^= JavaVersion.VERSION_1_8
		echo     targetCompatibility ^= JavaVersion.VERSION_1_8
		echo }
		echo.
		echo repositories {
		echo     mavenCentral^(^)
		echo     flatDir {
		echo         dirs 'libs/Jmul'
		echo     }
		echo }
		echo.
		echo dependencies {
		echo     implementation name: 'jmul-2.1.2'
		echo.
		echo     testImplementation 'junit:junit:4.11'
		echo }
	) > "%gradleBuildFile1%"

%return%

@rem ================================================================================
@rem ===
@rem ===   Internal Subroutines
@rem ===

@rem --------------------------------------------------------------------------------
@rem ---
@rem ---   void defineMacros()
@rem ---
@rem ---   The subroutine defines required macros.
@rem ---

:defineMacros

	set "ifError=set foundErr=1&(if errorlevel 0 if not errorlevel 1 set foundErr=)&if defined foundErr"
	
	set "cprintln=echo"
	set "cprint=echo|set /p="
	
	set "return=exit /b"

%return%


@rem --------------------------------------------------------------------------------
@rem ---
@rem ---   void resetErrorlevel()
@rem ---
@rem ---   The subroutine resets the errorlevel.
@rem ---

:resetErrorlevel

%return% 0

@rem --------------------------------------------------------------------------------
@rem ---
@rem ---   void defineConstants()
@rem ---
@rem ---   Declares and initializes variables and constants.
@rem ---

:defineConstants

	set TRUE=1
	set FALSE=0

	set rootDir=%~dp0..\..\
	set projectDir=%rootDir%Sources\

	set tempDir=%rootDir%tmp\

	set directories.length=10

	set gradleDirectories[1]=%tempDir%
	set gradleDirectories[2]=%tempDir%Numbers\
	set gradleDirectories[3]=%tempDir%Numbers\lib\
	set gradleDirectories[4]=%tempDir%Numbers\lib\src\
	set gradleDirectories[5]=%tempDir%Numbers\lib\src\main\
	set gradleDirectories[6]=%tempDir%Numbers\lib\src\main\java\
	set gradleDirectories[7]=%tempDir%Numbers\lib\src\main\resources\
	set gradleDirectories[8]=%tempDir%Numbers\lib\src\test\
	set gradleDirectories[9]=%tempDir%Numbers\lib\src\test\java\
	set gradleDirectories[10]=%tempDir%Numbers\lib\src\test\resources\

	set sources.length=4

	set sources[1]=%projectDir%Numbers\src\
	set sources[2]=%projectDir%Numbers\properties\
	set sources[3]=%projectDir%Numbers-Tests\src\
	set sources[4]=%projectDir%Version\properties\

	set gradleSettingsFile1=%gradleDirectories[2]%settings.gradle
	set gradleSettingsFile2=%gradleDirectories[2]%settings.gradle.kts
	set gradleBuildFile1=%gradleDirectories[3]%build.gradle
	set gradleBuildFile2=%gradleDirectories[3]%build.gradle.kts

%return%

@rem --------------------------------------------------------------------------------
@rem ---
@rem ---   void deleteFile(String _path)
@rem ---
@rem ---   Deletes the specified file.
@rem ---
@rem ---
@rem ---   @param _path
@rem ---          the specified path represents a file
@rem ---

:deleteFile

	set "_path=%1"
	if '%_path%'=='' (

		echo No file path has been specified! >&2
		%return% 2
	)
	set "_path=%_path:"=%"


	if exist %_path% (

		echo deleting %_path%
		del /S /Q %_path%

	) else (

		echo %_path% doesn't exist.
	)


	set _path=

%return%
